name = "ybadges-back"
main = "src/index.ts"
compatibility_date = "2023-12-18"
node_compat = true

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/workers/platform/environment-variables
[vars]
PSQL_CONNECTION_STRING = "postgresql://dev:2r9ytUFLCYRf@ep-curly-grass-80149002.eu-central-1.aws.neon.tech/Ybadge?sslmode=require"

